name: Build Quasar App

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Quasar SPA
        run: npx quasar build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: quasar-build
          path: dist/
