name: Playwright Tests
on:
  push:
    branches: [ main, master, testing ]
  pull_request:
    branches: [ main, master, testing ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Start Quasar dev server
      run: |
        npm run dev &
        sleep 10
    - name: Run Playwright tests
      run: npx playwright test --reporter=github
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
