name: Basic Test

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Hello World
        run: echo "Hello World - GitHub Actions is working!"
